
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/central_auth_service"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8080
  servlet:
    context-path: /identity
springdoc:
  api-docs:
    path: /v1/api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.engine.jdbc.spi.SqlExceptionHelper: ERROR

jwt:
  signerKey: "60de726f31ded068a7a1d7fe75e76c1aed2c91ee339eed322e5bfe3f9e9a0a66"